export const WEBSOCKET_CONNECTING = 'OPENBOT.WEBSOCKET_CONNECTING';
export const WEBSOCKET_CONNECTED = 'OPENBOT.WEBSOCKET_CONNECTED';
export const WEBSOCKET_CONNECTIONERROR = 'OPENBOT.WEBSOCKET_CONNECTIONERROR';
export const WEBSOCKET_CONNECTIONTIMEOUT =
  'OPENBOT.WEBSOCKET_CONNECTIONTIMEOUT';
export const WEBSOCKET_ERROR = 'OPENBOT.WEBSOCKET_ERROR';
export const WEBSOCKET_DISCONNECT = 'OPENBOT.WEBSOCKET_DISCONNECT';
export const WEBSOCKET_RECONNECT = 'OPENBOT.WEBSOCKET_RECONNECT';
export const WEBSOCKET_RECONNECTING = 'OPENBOT.WEBSOCKET_RECONNECTING';
export const WEBSOCKET_RECONNECTERROR = 'OPENBOT.WEBSOCKET_RECONNECTERROR';

export const MANUAL_ACTIVATION = 'OPENBOT.MANUAL_ACTIVATION';
export const NO_CARD = 'OPENBOT.NO_CARD';
